packages:
  - "apps/main/app"
  - "apps/main/base-app"
  - "apps/main/blueprint-forms"
  - "apps/main/blueprint-studio-theme"
  - "apps/main/ckeditor4-plugin"
  - "apps/main/ckeditor5"
  - "apps/main/ckeditor5-plugin"
  - "apps/main/controlroom-studio-plugin"
  - "apps/main/ec-studio"
  - "apps/main/ec-studio-model"
  - "apps/main/ec-studio-test-helper"
  - "apps/main/extension-config/extension-dependencies"
  - "apps/main/extension-config/static-extension-dependencies"
  - "apps/main/extensions/alx"
  - "apps/main/extensions/alx-google"
  - "apps/main/extensions/alx-webtrends"
  - "apps/main/extensions/am"
  - "apps/main/extensions/catalog"
  - "apps/main/extensions/create-from-template"
  - "apps/main/extensions/custom-topic-pages"
  - "apps/main/extensions/es"
  - "apps/main/extensions/es-alx"
  - "apps/main/extensions/lc-asset"
  - "apps/main/extensions/lc-es"
  - "apps/main/extensions/lc-p13n"
  - "apps/main/extensions/lc/lc-studio"
  - "apps/main/extensions/lc/lc-studio-test-helper"
  - "apps/main/extensions/osm"
  - "apps/main/extensions/p13n"
  - "apps/main/extensions/taxonomy"
  - "apps/main/extensions/training"
  - "apps/main/extensions/validators"
  - "apps/workflow/app"
  - "apps/workflow/extension-config/extension-dependencies"
  - "apps/workflow/extensions/alx"
  - "apps/workflow/extensions/alx-google"
  - "apps/workflow/extensions/alx-webtrends"
  - "apps/workflow/extensions/am"
  - "apps/workflow/extensions/catalog"
  - "apps/workflow/extensions/es"
  - "apps/workflow/extensions/lc"
  - "apps/workflow/extensions/p13n"
  - "global/studio"
  - "shared/js/blueprint-doctypes"
  - "shared/js/ecommerce-doctypes"
  - "shared/js/extensions/alx"
  - "shared/js/extensions/alx-google"
  - "shared/js/extensions/alx-webtrends"
  - "shared/js/extensions/am"
  - "shared/js/extensions/catalog"
  - "shared/js/extensions/es"
  - "shared/js/extensions/lc"
  - "shared/js/extensions/p13n"
  - "tools/localization-converter"
